### ISSUE TITLE
Do you have a way to find C++ includes that are unused?

### ISSUE THREAD

**Issue by bbusemeyer** [Wentzell/dotfiles#1]
I've seen online that it should be possible, but I haven't gotten it to work on my setup.

For example,
https://www.reddit.com/r/neovim/comments/rtpbpg/sort_and_remove_redundant_imports/

**Comment by Wentzell** [comment]
I have not managed to obtain this information within VIM through clangd unfortunately.

If you however manually run [iwyu](https://include-what-you-use.org/) on your build directory (containing the compile_commands.json) you should be able to get this info on the command line for all your files.

```
iwyu_tool.py -p path_to_builddir
```

At this time the clang-15 compatable release for iwyu is not out, but you can generate a llvm-14.0.6 build including iwyu using my build script. Remember to change the version numbers and to uncomment the iwyu part https://github.com/Wentzell/dotfiles/blob/cb5677eb336b31b8c0fd442ab8d1754ae05243cc/bin/build_llvm.sh#L94-L103

**Comment by bbusemeyer** [comment]
Do you know what precisely `iwyu_tool.py` is supposed to do? I tried it, but I see a lot of errors about not able to find stdlib headers. After it runs for a long time, I look and see nothing has changed. Is it supposed to produce an output file?

**Comment by Wentzell** [comment]
Please have a look at the [documentation](https://github.com/include-what-you-use/include-what-you-use/blob/master/README.md) of include what you use. It looks like there is now also integrated CMake support, which may be easier than using the `iwyu_tool.py`

**Comment by bbusemeyer** [comment]
Unfortunately I didn't have much lock with `iwyu_tool.py`, it seemed to think quite a few imports were unnecessary that actually were. I think I probably wasn't doing something right, and didn't have any more time to spend on it. The project I'm working on uses vanilla Make instead of CMake, as well, which I think complicates things.
